apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: llm-usage-ext-proc
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      maas: inference

  configPatches:
    - applyTo: CLUSTER
      patch:
        operation: ADD
        value:
          name: llm-ext-proc-cluster
          type: STRICT_DNS
          connect_timeout: 5s
          lb_policy: ROUND_ROBIN
          dns_lookup_family: V4_ONLY
          typed_extension_protocol_options:
            envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
              "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
              explicit_http_config:
                http2_protocol_options: {}
          load_assignment:
            cluster_name: llm-ext-proc-cluster
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: llm-ext-proc.istio-system.svc.cluster.local
                          port_value: 8888

    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: INSERT_FIRST
        value:
          name: envoy.filters.http.ext_proc
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor
            grpc_service:
              envoy_grpc:
                cluster_name: llm-ext-proc-cluster