#!/usr/bin/env bash
# scripts/run_bench.sh — 一键运行三种 JSON 解析方案的 benchmark 并生成对比报告
#
# 用法（WSL / Linux）:
#   bash scripts/run_bench.sh              # 默认 5s 每组
#   bash scripts/run_bench.sh -benchtime=10s
#   bash scripts/run_bench.sh -count=3     # 每组跑 3 轮取中位数
#
# 依赖: go ≥1.22, python3, lscpu, free
# 输出: build/bench_report_<timestamp>.md

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_DIR"

TIMESTAMP="$(date +%Y%m%d_%H%M%S)"
REPORT="build/bench_report_${TIMESTAMP}.md"
BENCH_ARGS="${*:-"-benchtime=5s"}"

# ── 1. 生成测试数据 ──────────────────────────────────────────────────────
if [ ! -f internal/resp/testdata/sse_events.jsonl ]; then
    echo ">> Generating test data..."
    python3 scripts/gen_testdata.py
fi

# ── 2. 采集环境信息 ──────────────────────────────────────────────────────
echo ">> Collecting system info..."

GO_VERSION="$(go version)"
GO_ENV="$(go env GOARCH GOOS CGO_ENABLED 2>/dev/null || echo 'N/A')"

# 硬件
CPU_MODEL="$(lscpu 2>/dev/null | grep 'Model name' | sed 's/.*:\s*//' || echo 'N/A')"
CPU_CORES="$(nproc 2>/dev/null || echo 'N/A')"
MEM_TOTAL="$(free -h 2>/dev/null | awk '/^Mem:/{print $2}' || echo 'N/A')"
MEM_AVAIL="$(free -h 2>/dev/null | awk '/^Mem:/{print $7}' || echo 'N/A')"

# 系统
OS_INFO="$(uname -srm 2>/dev/null || echo 'N/A')"
KERNEL="$(uname -r 2>/dev/null || echo 'N/A')"

# 库版本
GJSON_VER="$(go list -m -json github.com/tidwall/gjson 2>/dev/null | grep '"Version"' | head -1 | sed 's/.*"Version": "//;s/".*//' || echo 'N/A')"
SONIC_VER="$(go list -m -json github.com/bytedance/sonic 2>/dev/null | grep '"Version"' | head -1 | sed 's/.*"Version": "//;s/".*//' || echo 'N/A')"
JSONITER_VER="$(go list -m -json github.com/json-iterator/go 2>/dev/null | grep '"Version"' | head -1 | sed 's/.*"Version": "//;s/".*//' || echo 'N/A')"

# 测试数据统计
DATA_LINES="$(wc -l < internal/resp/testdata/sse_events.jsonl | tr -d ' ')"
DATA_SIZE="$(du -h internal/resp/testdata/sse_events.jsonl | cut -f1)"

# ── 3. 写入报告头部 ──────────────────────────────────────────────────────
cat > "$REPORT" <<EOF
# JSON 解析方案 Benchmark 报告

> 生成时间: $(date '+%Y-%m-%d %H:%M:%S %Z')

## 环境信息

| 项目 | 值 |
|------|-----|
| OS | ${OS_INFO} |
| Kernel | ${KERNEL} |
| CPU | ${CPU_MODEL} (${CPU_CORES} cores) |
| Memory | ${MEM_TOTAL} (available: ${MEM_AVAIL}) |
| Go | ${GO_VERSION} |
| GOARCH / GOOS / CGO | ${GO_ENV} |

## 依赖版本

| 库 | 版本 |
|----|------|
| json-iterator/go | ${JSONITER_VER} |
| tidwall/gjson | ${GJSON_VER} |
| bytedance/sonic | ${SONIC_VER} |

## 测试数据

| 项目 | 值 |
|------|-----|
| 文件 | \`internal/resp/testdata/sse_events.jsonl\` |
| 条数 | ${DATA_LINES} |
| 大小 | ${DATA_SIZE} |

## Benchmark 参数

\`\`\`
${BENCH_ARGS}
\`\`\`

---

EOF

# ── 4. 运行 benchmark ────────────────────────────────────────────────────

run_bench() {
    local label="$1"
    local tag="$2"
    local tag_flag=""
    if [ -n "$tag" ]; then
        tag_flag="-tags $tag"
    fi

    echo ">> Benchmarking: ${label} ..."
    echo "## ${label}" >> "$REPORT"
    echo "" >> "$REPORT"
    echo '```' >> "$REPORT"

    # shellcheck disable=SC2086
    go test -bench=. -benchmem -run=^$ ${tag_flag} ${BENCH_ARGS} ./internal/resp/ 2>&1 | tee -a "$REPORT"

    echo '```' >> "$REPORT"
    echo "" >> "$REPORT"
}

run_bench "default (json-iterator)" ""
run_bench "gjson (path extract)" "gjson"
run_bench "sonicjson (sonic JIT)" "sonicjson"

# ── 5. 汇总 ──────────────────────────────────────────────────────────────
echo "---" >> "$REPORT"
echo "" >> "$REPORT"
echo "_Report generated by \`scripts/run_bench.sh\`_" >> "$REPORT"

echo ""
echo ">> Report saved to: ${REPORT}"
